### ISSUE TITLE
Please use old Font again

### ISSUE THREAD

**Issue by bejohi** [qbin-io/frontend#4]
The new Font (implemented 2 weeks ago or so) means no progress and is much harder readable then the old one. Also some character sequences are converted, e.g. >=, !=, which is also harder to read (see attached screenshot).
![62890a04-443c-497d-bcf9-9af7cbf13ee3](https://user-images.githubusercontent.com/29673596/40832655-1772c6d8-658c-11e8-91c9-8e54d60242d8.jpeg)

**Comment by moqmar** [comment]
I can see where font ligatures can be a bit confusing for that and that the font is a bit too slim for some people - I thought while I was already making the size smaller I could try a new font but it seems like that backfired.

After also trying out a few other fonts right now, I actually found the old font to be the most readable, too. So, this is fixed now.
